"""
config.py — Central configuration for the vote prediction pipeline.

All defaults can be overridden via CLI arguments in run_pipeline.py.
The OpenRouter API key must be set as the environment variable:
    export OPENROUTER_API_KEY="sk-or-..."
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Load .env file
load_dotenv(Path(__file__).resolve().parent / ".env")

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
SRC_DIR = Path(__file__).resolve().parent.parent          # .../src/
DATA_DIR = SRC_DIR / "data"
RESULTS_DIR = SRC_DIR / "results"

HOUSE_VOTES_DIR  = DATA_DIR / "house_votes"
SENATE_VOTES_DIR = DATA_DIR / "senate_votes"
TWEETS_PKL       = DATA_DIR / "tweets_full.pkl"

# Pre-processed per-member vote CSVs (generated by preprocess_votes.py).
# Load these instead of parsing XMLs — fast, flat, ready to use.
HOUSE_MEMBERS_CSV  = DATA_DIR / "house_votes_members.csv"
SENATE_MEMBERS_CSV = DATA_DIR / "senate_votes_members.csv"

# Bill summary lookup CSVs (one row per vote_id, generated by
# data/bill_summaries_data.py from the congress.gov API).
HOUSE_BILL_SUMMARIES_CSV  = DATA_DIR / "house_bill_summaries.csv"
SENATE_BILL_SUMMARIES_CSV = DATA_DIR / "senate_bill_summaries.csv"

# Bill summaries longer than this are truncated (first N words) before
# being placed into prompts, to keep prompt size in check for large bills.
MAX_SUMMARY_WORDS = 500

# lis_member_id -> bioguide mapping (derived from legislators YAMLs)
LIS_TO_BIOGUIDE_CSV = DATA_DIR / "legislators" / "lis_to_bioguide.csv"

SOCIAL_MEDIA_YAMLS = [
    DATA_DIR / "social_media_handles" / "legislators-social-media_2014.yaml",
    DATA_DIR / "social_media_handles" / "legislators-social-media_2016.yaml",
    DATA_DIR / "social_media_handles" / "legislators-social-media_2018.yaml",
    DATA_DIR / "social_media_handles" / "legislators-social-media_2020.yaml",
    DATA_DIR / "social_media_handles" / "legislators-social-media_2021.yaml",
    DATA_DIR / "social_media_handles" / "legislators-social-media_2023.yaml",
    DATA_DIR / "social_media_handles" / "legislators-social-media_2025.yaml",
]

PREDICTIONS_CSV = RESULTS_DIR / "predictions.csv" #"/Users/jonahhartmann/Desktop/Master/Masterarbeit/predictions_3_7_yae_nay.csv"

# Baselines, written by run_baseline.py.
#
# Legacy variants. Both condition on the realized roll call — they read the
# tally of the very vote being predicted, which is not available at prediction
# time. Kept for reference only; not comparable to the LLM pipeline, which sees
# nothing after vote_date.
BASELINE_MAJORITY_CSV = RESULTS_DIR / "baseline_majority.csv"
BASELINE_PARTY_CSV    = RESULTS_DIR / "baseline_party.csv"

# Causal baselines — use only information available strictly before vote_date,
# matching the constraints the LLM pipeline runs under. These are the baselines
# to report against the LLM.
BASELINE_ALWAYS_YEA_CSV      = RESULTS_DIR / "baseline_always_yea.csv"
BASELINE_MEMBER_PRIOR_CSV    = RESULTS_DIR / "baseline_member_prior.csv"
BASELINE_PARTY_PRIOR_CSV     = RESULTS_DIR / "baseline_party_prior.csv"
BASELINE_CHAMBER_MAJORITY_CSV = RESULTS_DIR / "baseline_chamber_majority.csv"

MEMBERS_WITH_TWEETS_PKL    = DATA_DIR / "members_with_tweets.pkl"
MEMBERS_WITHOUT_TWEETS_PKL = DATA_DIR / "members_without_tweets.pkl"

LOADED_VOTES_CSV = DATA_DIR / "loaded_votes.csv"

AUTHOR_ID_DICT  = SRC_DIR / "author_id_dict.json"
AUTHOR_ID_DICT2 = SRC_DIR / "author_id_dict_2.json"

# Fuzzy-matched author_id -> bioguide (generated by fuzzy_match.py)
FUZZY_MATCH_CONFIRMED = DATA_DIR / "fuzzy_match_confirmed.csv"

STRATIFIED_SAMPLE_CSV = DATA_DIR / "stratified_sample.csv"

# ---------------------------------------------------------------------------
# LLM / OpenRouter
# ---------------------------------------------------------------------------
OPENROUTER_BASE_URL = "https://openrouter.ai/api/v1"

USE_LOCAL_MODEL = os.environ.get("USE_LOCAL_MODEL", "true").lower() == "true"
VLLM_BASE_URL = os.environ.get("VLLM_BASE_URL", "http://localhost:8000/v1")

DEFAULT_MODEL = "Qwen/Qwen2.5-32B-Instruct-AWQ"#"tclf90/qwen2.5-72b-instruct-gptq-int3"
MODEL         = "meta-llama/llama-3.3-70b-instruct:free"

def get_base_url() -> str:
    return VLLM_BASE_URL if USE_LOCAL_MODEL else OPENROUTER_BASE_URL

def get_api_key() -> str:
    if USE_LOCAL_MODEL:
        return "not-needed"
    key = os.environ.get("OPENROUTER_API_KEY", "").strip()
    if not key:
        raise EnvironmentError(
            "OPENROUTER_API_KEY environment variable is not set."
        )
    return key

# ---------------------------------------------------------------------------
# Feature defaults
# ---------------------------------------------------------------------------
N_DAYS_TWEETS      = 100     # days before vote date to look for tweets
MAX_TWEETS_RAW     = 150    # tweets collected from window and sent to retrieval
MAX_TWEETS_PROMPT  = 25   # tweets in final prediction prompt (after retrieval)
N_PAST_VOTES       = 25     # number of past votes to include in prompt
SKIP_RETRIEVAL     = False  # if True, skip tweet relevance filtering

# ---------------------------------------------------------------------------
# LLM call settings
# ---------------------------------------------------------------------------
MAX_RETRIES     = 3
TEMPERATURE     = 0.0    # deterministic predictions
MAX_TOKENS      = 1000
REQUEST_DELAY   = 0.0 if USE_LOCAL_MODEL else 2.0
MAX_CONCURRENCY = 40 if USE_LOCAL_MODEL else 1

# ---------------------------------------------------------------------------
# Topic modelling / topic-based tweet retrieval
# ---------------------------------------------------------------------------
# Retrieval strategy: "llm" (LLM relevance judgment), "topic" (topic-model
# gating), or "none" (raw tweets, equivalent to --skip-retrieval).
RETRIEVAL_METHOD = "llm"

# Cleaned tweet corpus used for topic modelling. Built separately — must
# contain the columns: id, bioguide_id, created_at, text.
# NOTE: deliberately separate from TWEETS_PKL above, which is left untouched.
TWEETS_TOPIC_PKL = DATA_DIR / "tweets_full.pkl"

TOPIC_DIR              = DATA_DIR / "topic_model"
TOPIC_MODEL_DIR        = TOPIC_DIR / "bertopic"
TWEET_TOPICS_PARQUET   = TOPIC_DIR / "tweet_topics.parquet"
TWEET_EMBEDDINGS_NPY   = TOPIC_DIR / "tweet_embeddings.npy"
VOTE_TOPICS_PARQUET    = TOPIC_DIR / "vote_topics.parquet"
TOPIC_INFO_CSV         = TOPIC_DIR / "topic_info.csv"

# Sentence embedding model used for both tweets and bill text.
#   all-mpnet-base-v2  — 768-dim, best quality, ~3x slower
#   all-MiniLM-L6-v2   — 384-dim, ~3-5x faster, fine for topic modelling
EMBEDDING_MODEL      = "sentence-transformers/all-mpnet-base-v2"
EMBEDDING_BATCH_SIZE = 512    # 256 is conservative; a H100 handles 512-1024
EMBEDDING_DEVICE     = None   # None -> auto-detect (cuda / mps / cpu)
EMBEDDING_FP16       = True   # halve memory + roughly double speed on CUDA

# Sanity reference for the fit: on an H100, mpnet embeds several thousand
# tweets/second. If you see single- or double-digit it/s, you are on CPU —
# get_device() will warn loudly.

# Fitting. UMAP/HDBSCAN are fit on a subsample; the rest is transformed in
# chunks. Short tweets are excluded from FITTING only — they stay retrievable.
TOPIC_FIT_SAMPLE     = 750_000
TOPIC_MIN_FIT_WORDS  = 5
TOPIC_MIN_CLUSTER_SIZE = 200
TOPIC_NR_TOPICS      = "auto"   # or an int to force reduction

# Full-corpus assignment (TopicSpace.assign) rejects a tweet below this
# similarity floor and routes it to -1 ("unclassified") instead of forcing
# it into the nearest centroid. The floor is data-driven: computed at fit
# time as this percentile of the fit pool's own similarity-to-assigned-
# centroid distribution (persisted in topic_meta.json as
# "assign_min_similarity"), not a hardcoded constant.
TOPIC_ASSIGN_MIN_SIM_PERCENTILE = 5

# Bill summaries are chunked before embedding so a long summary is not
# averaged into mush; the vote vector is the max-pooled chunk similarity.
TOPIC_SUMMARY_CHUNK_WORDS = 200
TOPIC_MAX_SUMMARY_CHUNKS  = 8

# Retrieval scoring: score = TOPIC_WEIGHT * topic_sim + EMB_WEIGHT * emb_sim
TOPIC_WEIGHT  = 0.5
EMB_WEIGHT    = 0.5
TOPIC_TOP_K   = 25     # max tweets returned per candidate
TOPIC_MIN_SIM = 0.25   # score floor; 0.0 -> pure top-K, never empty

# ---------------------------------------------------------------------------
# Vote scope
# ---------------------------------------------------------------------------
# Nomination / confirmation votes have no bill text for the topic method to
# match against, and are near-perfectly party-line. Excluded from the
# tweet-augmented analysis. Set False to keep them.
DROP_NOMINATION_VOTES = True

# ---------------------------------------------------------------------------
# Stratified sampling
# ---------------------------------------------------------------------------
MIN_PER_STRATUM          = 30
COMPETITIVENESS_THRESHOLDS = (0.80, 0.80)  # Standard: contested < 80%, unanimous >= 80%

# ---------------------------------------------------------------------------
# Bootstrap
# ---------------------------------------------------------------------------
N_BOOTSTRAP  = 10000
BOOTSTRAP_CI = 0.95