"""
data_loader.py — Loads and normalises all raw data sources.

Vote data is loaded from pre-processed CSVs (generated by preprocess_votes.py).
Run that script once before using the pipeline.

Public API:
    load_votes(chamber="both")               -> pd.DataFrame
    load_tweets()                            -> pd.DataFrame
    build_tweet_index(tweets_df)             -> dict[bioguide -> pd.DataFrame]
"""

import json
import logging
from typing import Dict, Literal

import pandas as pd
import yaml

from . import config

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Votes
# ---------------------------------------------------------------------------

def load_votes(chamber: Literal["house", "senate", "both"] = "both") -> pd.DataFrame:
    """
    Load the pre-processed per-member vote CSVs produced by preprocess_votes.py.

    Columns: vote_id, vote_date, bill_number, bill_title, question,
             congress, session, bioguide, member_name, party, state,
             vote_cast, [lis_member_id — senate only]
    """
    dfs = []

    if chamber in ("house", "both"):
        if not config.HOUSE_MEMBERS_CSV.exists():
            raise FileNotFoundError(
                f"House votes CSV not found: {config.HOUSE_MEMBERS_CSV}\n"
                "Run:  python preprocess_votes.py"
            )
        logger.info("Loading house votes from %s …", config.HOUSE_MEMBERS_CSV.name)
        df = pd.read_csv(config.HOUSE_MEMBERS_CSV, parse_dates=["vote_date"], low_memory=False)
        dfs.append(df)
        logger.info("  → %d house member-vote rows.", len(df))

    if chamber in ("senate", "both"):
        if not config.SENATE_MEMBERS_CSV.exists():
            raise FileNotFoundError(
                f"Senate votes CSV not found: {config.SENATE_MEMBERS_CSV}\n"
                "Run:  python preprocess_votes.py"
            )
        logger.info("Loading senate votes from %s …", config.SENATE_MEMBERS_CSV.name)
        df = pd.read_csv(config.SENATE_MEMBERS_CSV, parse_dates=["vote_date"], low_memory=False)
        dfs.append(df)
        logger.info("  → %d senate member-vote rows.", len(df))

    combined = pd.concat(dfs, ignore_index=True)

    # Drop rows with no bioguide — can't link to tweets or past votes
    before = len(combined)
    combined.dropna(subset=["bioguide"], inplace=True)
    dropped = before - len(combined)
    if dropped:
        logger.warning("Dropped %d rows with no bioguide (%.1f%%).", dropped, dropped / before * 100)

    # Exclude "Not Voting" rows — pipeline only predicts Yea/Nay
    before = len(combined)
    combined = combined[combined["vote_cast"].isin(["Yea", "Nay"])].copy()
    logger.info("Excluded non-Yea/Nay votes: %d -> %d rows", before, len(combined))

    # # --- TEMP: restrict to votes on/after June 2024 for testing ---
    # cutoff = pd.Timestamp("2024-06-01")
    # before = len(combined)
    # combined = combined[combined["vote_date"] >= cutoff].copy()
    # logger.info("Filtered to votes >= %s: %d -> %d rows", cutoff.date(), before, len(combined))

    combined.sort_values("vote_date", inplace=True)
    combined.reset_index(drop=True, inplace=True)

    logger.info(
        "Loaded %d total member-vote rows | %d unique members | %d unique votes.",
        len(combined), combined["bioguide"].nunique(), combined["vote_id"].nunique(),
    )

    # Attach bill summaries (see bill_summaries_data.py) keyed by vote_id.
    summaries = load_bill_summaries()
    combined["bill_summary"] = combined["vote_id"].map(summaries).fillna("")
    combined["has_bill_summary"] = combined["bill_summary"].str.strip() != ""
    n_votes = combined["vote_id"].nunique()
    n_votes_with_summary = combined.loc[combined["has_bill_summary"], "vote_id"].nunique()
    logger.info(
        "Bill summary coverage: %d/%d unique votes have a summary (%.1f%%).",
        n_votes_with_summary, n_votes,
        n_votes_with_summary / n_votes * 100 if n_votes else 0,
    )

    return combined


def _truncate_words(text: str, max_words: int) -> str:
    """Truncate text to at most max_words words (whitespace-split)."""
    words = text.split()
    if len(words) <= max_words:
        return text
    return " ".join(words[:max_words]) + " …"


def load_bill_summaries() -> Dict[str, str]:
    """
    Load the congress.gov bill summary lookup CSVs (one row per vote_id,
    produced by data/bill_summaries_data.py) and return a vote_id -> summary
    text mapping. Votes with no resolvable bill or no summary map to "".

    Summaries longer than config.MAX_SUMMARY_WORDS are truncated.
    """
    summaries: Dict[str, str] = {}
    n_total = 0
    n_truncated = 0

    for path in (config.HOUSE_BILL_SUMMARIES_CSV, config.SENATE_BILL_SUMMARIES_CSV):
        if not path.exists():
            logger.warning(
                "Bill summaries CSV not found: %s — bill_summary will be empty "
                "for these votes. Run: python data/bill_summaries_data.py",
                path,
            )
            continue
        df = pd.read_csv(path, usecols=["vote_id", "summary_text"])
        for vote_id, text in zip(df["vote_id"], df["summary_text"]):
            if not isinstance(text, str) or not text:
                summaries[vote_id] = ""
                continue
            n_total += 1
            truncated = _truncate_words(text, config.MAX_SUMMARY_WORDS)
            if truncated != text:
                n_truncated += 1
            summaries[vote_id] = truncated

    if n_total:
        logger.info(
            "Bill summaries: %d/%d exceeded %d words and were truncated.",
            n_truncated, n_total, config.MAX_SUMMARY_WORDS,
        )

    return summaries


def save_loaded_votes(votes_df: pd.DataFrame) -> None:
    """Save the loaded votes DataFrame to CSV for post-hoc inspection."""
    votes_df.to_csv(config.LOADED_VOTES_CSV, index=False)
    logger.info("Saved loaded votes to %s (%d rows).", config.LOADED_VOTES_CSV.name, len(votes_df))


# ---------------------------------------------------------------------------
# Tweets
# ---------------------------------------------------------------------------

def load_tweets() -> pd.DataFrame:
    """
    Load the pre-built tweets_full.pkl.

    Relevant columns: id, author_id, created_at, text, handle, bioguide_id
    """
    logger.info("Loading tweets from %s …", config.TWEETS_PKL)
    df = pd.read_pickle(config.TWEETS_PKL)

    df["created_at"] = pd.to_datetime(df["created_at"], utc=True, errors="coerce")
    df["created_at"] = df["created_at"].dt.tz_localize(None)  # strip tz → naive UTC
    df.dropna(subset=["created_at"], inplace=True)
    df["handle"] = df["handle"].str.lower().str.strip()

    n_with_bio = df["bioguide_id"].notna().sum() if "bioguide_id" in df.columns else 0
    logger.info(
        "Loaded %d tweets from %d unique handles — %d (%.1f%%) have a bioguide_id.",
        len(df), df["handle"].nunique(),
        n_with_bio, n_with_bio / len(df) * 100 if len(df) else 0,
    )
    return df


def build_tweet_index(tweets_df: pd.DataFrame) -> Dict[str, pd.DataFrame]:
    """
    Build a bioguide -> DataFrame index from the tweets DataFrame.

    Relies on the ``bioguide_id`` column added to tweets_full.pkl by the
    notebook cell that maps twitter identifiers to bioguide IDs.  Tweets
    without a bioguide_id are silently excluded from the index (they cannot
    be linked to any member in the votes data).

    Returns
    -------
    dict[str, pd.DataFrame]
        Keys are bioguide strings; values are DataFrames containing at least
        ``created_at`` and ``text`` columns, sorted by ``created_at``
        descending so the most recent tweet comes first.
    """
    if "bioguide_id" not in tweets_df.columns:
        logger.error(
            "tweets_df has no 'bioguide_id' column.  "
            "Re-run the mapping notebook cell and rebuild tweets_full.pkl."
        )
        return {}

    mapped = tweets_df.dropna(subset=["bioguide_id"]).copy()
    mapped["bioguide_id"] = mapped["bioguide_id"].astype(str)

    index: Dict[str, pd.DataFrame] = {}
    for bioguide, group in mapped.groupby("bioguide_id", sort=False):
        index[bioguide] = (
            group.sort_values("created_at", ascending=False)
                 .reset_index(drop=True)
        )

    logger.info(
        "Tweet index built: %d members with at least one tweet "
        "(%d tweets total, %d tweets excluded — no bioguide_id).",
        len(index),
        len(mapped),
        len(tweets_df) - len(mapped),
    )
    return index


def log_coverage(votes_df: pd.DataFrame, tweet_index: Dict[str, pd.DataFrame]) -> None:
    """Log what fraction of members in the vote data have tweet coverage."""
    vote_members  = set(votes_df["bioguide"].dropna().unique())
    tweet_members = set(tweet_index.keys())
    covered   = vote_members & tweet_members
    uncovered = vote_members - tweet_members
    logger.info(
        "Tweet coverage: %d/%d members in vote data have tweets (%.1f%%). "
        "%d members will be predicted on past votes + party only.",
        len(covered), len(vote_members),
        len(covered) / len(vote_members) * 100 if vote_members else 0,
        len(uncovered),
    )


def save_member_splits(votes_df: pd.DataFrame, tweet_index: Dict[str, pd.DataFrame]) -> None:
    """
    Build per-member DataFrames and save covered / uncovered groups as pkl.

    One row per unique bioguide with columns:
        bioguide, member_name, party, state, chamber
    """
    member_rows = (
        votes_df.sort_values("vote_date", ascending=False)
        .drop_duplicates(subset=["bioguide"])
    )
    members = member_rows[["bioguide", "member_name", "party", "state", "chamber"]].copy()

    tweet_members = set(tweet_index.keys())
    covered   = members[members["bioguide"].isin(tweet_members)].reset_index(drop=True)
    uncovered = members[~members["bioguide"].isin(tweet_members)].reset_index(drop=True)

    covered.to_pickle(config.MEMBERS_WITH_TWEETS_PKL)
    uncovered.to_pickle(config.MEMBERS_WITHOUT_TWEETS_PKL)

    logger.info(
        "Saved member splits: %d with tweets → %s, %d without → %s",
        len(covered), config.MEMBERS_WITH_TWEETS_PKL.name,
        len(uncovered), config.MEMBERS_WITHOUT_TWEETS_PKL.name,
    )


def filter_to_covered(votes_df: pd.DataFrame, tweet_index: Dict[str, pd.DataFrame]) -> pd.DataFrame:
    """Return votes_df filtered to only members that appear in tweet_index."""
    covered_bioguides = set(tweet_index.keys())
    before = len(votes_df)
    filtered = votes_df[votes_df["bioguide"].isin(covered_bioguides)].copy()
    logger.info(
        "Filtered votes to covered members: %d → %d rows (%.1f%% kept).",
        before, len(filtered), len(filtered) / before * 100 if before else 0,
    )
    return filtered
